GET http://localhost:8080/

###

GET http://localhost:8080/detalhes/1


###
POST http://localhost:8080/cadastro
Content-Type: application/json

{
    "marca": "chevrolet",
    "modelo": "onix",
    "cor": "preto",
    "combustivel": "flex"

}
###
Get http://localhost:8080/deletar/1

###

POST http://localhost:8080/cadastro
Content-Type: application/json

{
    "id": 3,
    "marca": "audi",
    "modelo": "a3",
    "cor": "branco",
    "combustivel": "diesel"

}
